name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Node.js so Prettier can run reliably
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Optional: Install dependencies if you use a local Prettier config or plugins
      # - run: npm ci

      - name: Run Prettier (auto-fix style issues)
        run: npx prettier --write "src/**/*.{js,ts,jsx,tsx,css,md}"

      # Optionally, fail the workflow if there are uncommitted changes after Prettier runs
      # - name: Check for uncommitted changes
      #   run: |
      #     if [[ `git status --porcelain` ]]; then
      #       echo "Code style issues fixed by Prettier. Please commit the changes."
      #       exit 1
      #     fi